baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Rahul Myana'
theme = 'hermit'

[markup.goldmark.renderHooks.image]
enableDefault = true

[markup.goldmark.renderHooks.link]
enableDefault = true

[[module.mounts]]
source = 'assets'
target = 'assets'

[[module.mounts]]
source = 'attachments'
target = 'assets/attachments'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

enableRobotsTXT = true

[params]
  footerHideThemeName = true
  justifyContent = false
  
  scrollToTop = true
  readTime = true
  readTimeSeparator = "ðŸ•‘"

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/Ramenisneat"




[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10
